AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Group9CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: Group9CodeBuild
      Source:
        Type: CODEPIPELINE
        BuildSpec: "buildspec.yml"
        InsecureSsl: false
      Artifacts:
        Type: CODEPIPELINE
        Name: Group9CodeBuild
      Environment:
        Type: LINUX_CONTAINER
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: false
        ImagePullCredentialsType: CODEBUILD
      ServiceRole: "arn:aws:iam::122610523504:role/service-role/codebuild-Group9CodeBuild-service-role"
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: "arn:aws:kms:us-east-1:122610523504:alias/aws/s3"
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED
          EncryptionDisabled: false
      Tags: []  

Outputs:
  Group9CodeBuildName:
    Value: !Ref Group9CodeBuild
    Export:
      Name: Group9CodeBuildName
